// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test2.Infrastructure.Persistence;

#nullable disable

namespace Test2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250609073633_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test2.Domain.Models.AvailableProgram", b =>
                {
                    b.Property<int>("AvailableProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailableProgramId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("WashingMachineId")
                        .HasColumnType("int");

                    b.HasKey("AvailableProgramId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("WashingMachineId");

                    b.ToTable("AvailablePrograms");

                    b.HasData(
                        new
                        {
                            AvailableProgramId = 1,
                            Price = 1001m,
                            ProgramId = 1,
                            WashingMachineId = 1
                        });
                });

            modelBuilder.Entity("Test2.Domain.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            FirstName = "Arina",
                            LastName = "Liubas"
                        });
                });

            modelBuilder.Entity("Test2.Domain.Models.PurchaseHistory", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("AvailableProgramId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "AvailableProgramId");

                    b.HasIndex("AvailableProgramId");

                    b.ToTable("PurchaseHistories");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            AvailableProgramId = 1,
                            PurchaseDate = new DateTime(2004, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        });
                });

            modelBuilder.Entity("Test2.Domain.Models.WashingMachine", b =>
                {
                    b.Property<int>("WashingMachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WashingMachineId"));

                    b.Property<decimal>("MaxWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WashingMachineId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("WashingMachines");

                    b.HasData(
                        new
                        {
                            WashingMachineId = 1,
                            MaxWeight = 15m,
                            SerialNumber = "a2"
                        });
                });

            modelBuilder.Entity("Test2.Domain.Models.WashingProgram", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureCelsius")
                        .HasColumnType("int");

                    b.HasKey("ProgramId");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            ProgramId = 1,
                            DurationMinutes = 30,
                            Name = "Quick Wash",
                            TemperatureCelsius = 40
                        },
                        new
                        {
                            ProgramId = 2,
                            DurationMinutes = 90,
                            Name = "Cotton Cycle",
                            TemperatureCelsius = 60
                        },
                        new
                        {
                            ProgramId = 3,
                            DurationMinutes = 45,
                            Name = "Synthetic",
                            TemperatureCelsius = 50
                        });
                });

            modelBuilder.Entity("Test2.Domain.Models.AvailableProgram", b =>
                {
                    b.HasOne("Test2.Domain.Models.WashingProgram", "Program")
                        .WithMany("AvailablePrograms")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test2.Domain.Models.WashingMachine", "WashingMachine")
                        .WithMany("AvailablePrograms")
                        .HasForeignKey("WashingMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("WashingMachine");
                });

            modelBuilder.Entity("Test2.Domain.Models.PurchaseHistory", b =>
                {
                    b.HasOne("Test2.Domain.Models.AvailableProgram", "AvailableProgram")
                        .WithMany("Purchases")
                        .HasForeignKey("AvailableProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test2.Domain.Models.Customer", "Customer")
                        .WithMany("Purchases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailableProgram");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Test2.Domain.Models.AvailableProgram", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Test2.Domain.Models.Customer", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Test2.Domain.Models.WashingMachine", b =>
                {
                    b.Navigation("AvailablePrograms");
                });

            modelBuilder.Entity("Test2.Domain.Models.WashingProgram", b =>
                {
                    b.Navigation("AvailablePrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
